version: '3.2'

services:

  nginx-web:
    restart: always
    build: ./nginx
    ports:
      - "88:88"
    volumes:
        - "./nginx/volume:/code"
    links:
      - nodejs-server:nodejs-server

  nodejs-server:
      build: ./nodejs-server
      volumes:
        - "./nodejs-server/app-vol:/opt/nodejs/emp"
      ports:
        - "5003:5003"
